//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InContact.DeveloperPortal.Web.LuceneSearch {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchResult", Namespace="http://schemas.datacontract.org/2004/07/InContact.LuceneSearchService.LuceneSearc" +
        "hResults")]
    [System.SerializableAttribute()]
    public partial class SearchResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlerbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Blerb {
            get {
                return this.BlerbField;
            }
            set {
                if ((object.ReferenceEquals(this.BlerbField, value) != true)) {
                    this.BlerbField = value;
                    this.RaisePropertyChanged("Blerb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LuceneSearch.ILuceneSearch")]
    public interface ILuceneSearch {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILuceneSearch/SearchForData", ReplyAction="http://tempuri.org/ILuceneSearch/SearchForDataResponse")]
        System.Collections.Generic.List<InContact.DeveloperPortal.Web.LuceneSearch.SearchResult> SearchForData(string queryString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILuceneSearch/SearchForData", ReplyAction="http://tempuri.org/ILuceneSearch/SearchForDataResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<InContact.DeveloperPortal.Web.LuceneSearch.SearchResult>> SearchForDataAsync(string queryString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILuceneSearch/ReIndex", ReplyAction="http://tempuri.org/ILuceneSearch/ReIndexResponse")]
        string ReIndex(bool value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILuceneSearch/ReIndex", ReplyAction="http://tempuri.org/ILuceneSearch/ReIndexResponse")]
        System.Threading.Tasks.Task<string> ReIndexAsync(bool value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILuceneSearch/AddDocumentToSearch", ReplyAction="http://tempuri.org/ILuceneSearch/AddDocumentToSearchResponse")]
        string AddDocumentToSearch(InContact.DeveloperPortal.Web.LuceneSearch.SearchResult inputDocument);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILuceneSearch/AddDocumentToSearch", ReplyAction="http://tempuri.org/ILuceneSearch/AddDocumentToSearchResponse")]
        System.Threading.Tasks.Task<string> AddDocumentToSearchAsync(InContact.DeveloperPortal.Web.LuceneSearch.SearchResult inputDocument);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILuceneSearch/updateDocument", ReplyAction="http://tempuri.org/ILuceneSearch/updateDocumentResponse")]
        string updateDocument(InContact.DeveloperPortal.Web.LuceneSearch.SearchResult document, string prevBlerb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILuceneSearch/updateDocument", ReplyAction="http://tempuri.org/ILuceneSearch/updateDocumentResponse")]
        System.Threading.Tasks.Task<string> updateDocumentAsync(InContact.DeveloperPortal.Web.LuceneSearch.SearchResult document, string prevBlerb);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILuceneSearchChannel : InContact.DeveloperPortal.Web.LuceneSearch.ILuceneSearch, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LuceneSearchClient : System.ServiceModel.ClientBase<InContact.DeveloperPortal.Web.LuceneSearch.ILuceneSearch>, InContact.DeveloperPortal.Web.LuceneSearch.ILuceneSearch {
        
        public LuceneSearchClient() {
        }
        
        public LuceneSearchClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LuceneSearchClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LuceneSearchClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LuceneSearchClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<InContact.DeveloperPortal.Web.LuceneSearch.SearchResult> SearchForData(string queryString) {
            return base.Channel.SearchForData(queryString);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<InContact.DeveloperPortal.Web.LuceneSearch.SearchResult>> SearchForDataAsync(string queryString) {
            return base.Channel.SearchForDataAsync(queryString);
        }
        
        public string ReIndex(bool value) {
            return base.Channel.ReIndex(value);
        }
        
        public System.Threading.Tasks.Task<string> ReIndexAsync(bool value) {
            return base.Channel.ReIndexAsync(value);
        }
        
        public string AddDocumentToSearch(InContact.DeveloperPortal.Web.LuceneSearch.SearchResult inputDocument) {
            return base.Channel.AddDocumentToSearch(inputDocument);
        }
        
        public System.Threading.Tasks.Task<string> AddDocumentToSearchAsync(InContact.DeveloperPortal.Web.LuceneSearch.SearchResult inputDocument) {
            return base.Channel.AddDocumentToSearchAsync(inputDocument);
        }
        
        public string updateDocument(InContact.DeveloperPortal.Web.LuceneSearch.SearchResult document, string prevBlerb) {
            return base.Channel.updateDocument(document, prevBlerb);
        }
        
        public System.Threading.Tasks.Task<string> updateDocumentAsync(InContact.DeveloperPortal.Web.LuceneSearch.SearchResult document, string prevBlerb) {
            return base.Channel.updateDocumentAsync(document, prevBlerb);
        }
    }
}
