
import apiMethods
import sys

#sample data
contactId = '2237919921'
agentId = '210452'
skillId = '162779'
teamId = '38077'
groupId = '10001'
accessKeyId= '4FE4QQJVVDVJZWQ7NGBE4YF35O7DEHRJ74XPPQNQ3MYYKFNHIYBA===='

apiMethods.init()
#get accessToken
access_token = apiMethods.getAccessToken()
#accessToken validation
if access_token == None:
    print("invalid access token")
    sys.exit()
#get sessionID
# sessionID = apiMethods.generateAgentSession()

# #session ID validation
# if sessionID == None:
    # print("invalid sessionID")
    # sys.exit()


print("__________________")
print("API invoke Started : ")
print("__________________")
# apiMethods.getStandardAddressBookEntries('12345','','','','','','')
# apiMethods.PostAgent()

# apiMethods.getAgentSkillsByAgentId(agentId,'','','','','','','','')
# apiMethods.PutAgentbyAgentID(agentId)
# apiMethods.GetagentbyAgentID(agentId)
# apiMethods.GetAgentByAgentIDGroups(agentId,'')
# apiMethods.PostAgentMessages('hi','2018-02-07T06:22:27.143Z','hi',agentId,'Agent','2018-02-07T06:23:27.143Z','5')
# apiMethods.deleteAgentMessagesByMessageId('12345')
# apiMethods.getTeam('','','','','','')
# apiMethods.PutTeam()
# apiMethods.PutTeambyTeamID(teamId)
# apiMethods.GetTeamAgent('','')
# apiMethods.GetTeamByAgentID(teamId,'')
# apiMethods.GetBrandingProfile('1043','')
# apiMethods.GetDispostion('','','','','','','')
# apiMethods.DeleteFiles('sample')
# apiMethods.PostCreateFileName('rafiqSample', 'MTAwMQlNaXNzaW5nIEV4dGVybmFsIElELg0KMTAwMglNaXNzaW5nIEV4dGVybmFsIElELg0KMTAwMwlNaXNzaW5nIEV4dGVybmFsIElELg0KMTAwNAlNaXNzaW5nIEV4dGVybmFsIElELg0KMTAwNQlNaXNzaW5nIEV4dGVybmFsIElELg0KMTAwNglNaXNzaW5nIEV4dGVybmFsIElELg0K', 'true')
# apiMethods.PutupdateFile( 'rafiqSample', 'rafiqSample','true')
# apiMethods.GetFilesExternal('CallingLists')
# apiMethods.PostCreateFileExternal('testfile','MTAwMQlNaXNzaW5nIEV4dGVybmFsIElELg0KMTAwMglNaXNzaW5nIEV4dGVybmFsIElELg0KMTAwMwlNaXNzaW5nIEV4dGVybmFsIElELg0KMTAwNAlNaXNzaW5nIEV4dGVybmFsIElELg0KMTAwNQlNaXNzaW5nIEV4dGVybmFsIElELg0KMTAwNglNaXNzaW5nIEV4dGVybmFsIElELg0K','true','true')
# apiMethods.PutupdateFilesExternal('testfile','false')
# apiMethods.DeleteFolders('folderName')
# apiMethods.GetFolders('CallingLists')
# apiMethods.PostcreateDispositions('dip2332','false',5)
# apiMethods.GetDispostionByID('4552','')
# apiMethods.PutUpdateDispostionbydispositionId('5','dip2332','false','1', 'true')
# apiMethods.GetDispostionByClassification('')
# apiMethods.PostCreateSkill()
# apiMethods.PutSkillbySkillID(skillId)
# apiMethods.GetDispostionBySkillid(skillId,'','','','','' )
# apiMethods.GetDispostionBySkillidUnAssigned(skillId,'','','','','')
# apiMethods.GetSkillParameterGeneralSetting('165455','') # personal call skill id
# apiMethods.PutSkillParameterGeneralSetting('165455') # personal call skill id
# apiMethods.GetcontactbyContactID(contactId,'')
# apiMethods.GetListCalllist('','','','','2017-09-15T15:53:00','2017-09-15T15:53:00')
# apiMethods.PostCallListbyListID('1001',skillId,'','true','','','','false')
# apiMethods.GetCallingListbyJobID('1001','')
# apiMethods.GetGroups('10000','','groupId','','true','')
# apiMethods.PostGroups('sample','true','sample')
# apiMethods.GetGroupsByGroupID(groupId,'')    #sample Group ID
# apiMethods.PutGroupsByGroupID(groupId,'sample','true','sample')   # sample Group ID
# apiMethods.DeleteGroupsByAgentGroupID(groupId,'101212') # sample Group ID
# apiMethods.GetGroupsByAgentGroupID(groupId,'','','','','','')# sample Group ID
# apiMethods.PostGroupsByAgentGroupID(groupId,'101212')# sample Group ID
# apiMethods.postSessionIdInteractionsContactIdtyping(sessionID, '2237919812','true','true')
# apiMethods.posttAgentSessionSessionIdInteractionAddEmail(sessionID)
# apiMethods.posttAgentSessionIdInteractionConatactIdParkemail(sessionID,contactId)
# apiMethods.posttAgentSessionIdInteractionConatactIdUnparkemail( sessionID, contactId)
# apiMethods.posttAgentSessionIdInteractionConatactIdPreview( sessionID, contactId)
# apiMethods.posttAgentSessionIdInteractionConatactIdEmailRestore(sessionID, contactId)
# apiMethods.posttAgentSessionIdInteractionConatactIdSnooze( sessionID, contactId)
# apiMethods.DialCallback(sessionID, contactId)
# apiMethods.RescheduleCallback( sessionID, contactId,'2008-09-15T15:53:00')
# apiMethods.CancelCallback(sessionID,contactId , 'hi')
# apiMethods.posttAgentSessionIdAddcontact(sessionID)
# apiMethods.posttAgentSessionIdInteractionConatactIdActivate(sessionID, contactId)
#apiMethods.GetSmstranscripts( '2018-03-01T15:53:00', '2018-03-15T15:53:00','12345','','','')
# apiMethods.GetSmstranscriptsbyContactid( '2238306091','2018-03-01T15:53:00', '2018-03-15T15:53:00','1245', '','')
# apiMethods.GetTeamPerformancebyTeamIDTotal( '1138', '2018-02-28', '2018-03-01')
# apiMethods.getReportJobById('12345')
# apiMethods.GetdatadownloadbyReportID('1','sample.csv','2018-02-28','2018-03-01','','') # It seems that the server to which you are sending the Post request(your Site's server) has been configured to block Post request.
# apiMethods.Getwfoascm('2018-02-28T15:53:00','2018-02-28T15:53:00' )
# apiMethods.Getwfoasi('2018-02-28T15:53:00','2018-02-28T15:53:00' )
# apiMethods.Getwfocsi('2018-02-28T15:53:00','2018-02-28T15:53:00' )
# apiMethods.Getwfoftci('2018-02-28T15:53:00','2018-02-28T15:53:00' )
# apiMethods.Getwfoosi('2018-02-28T15:53:00','2018-02-28T15:53:00' )
# apiMethods.Getwfoqm('2018-02-28T15:53:00','2018-02-28T15:53:00' )
# apiMethods.GetTeamPerformanceTotal('2018-02-28','2018-03-01')
# apiMethods.GetwfmSkillContacts('2018-02-28T15:53:00','2018-03-02T15:53:00','1')
# apiMethods.Getwfmagetns('2018-02-28T15:53:00','2018-03-02T15:53:00')
# apiMethods.GetwfmdailerContacts('2018-02-28T15:53:00','2018-03-02T15:53:00')
# apiMethods.Getwfmscheduleadherence('2018-02-28T15:50:00','2018-02-28T15:53:00')
# apiMethods.GetwfmAgentscorecard('2018-02-28T15:50:00','2018-02-28T15:53:00')
# apiMethods.GetwfmAgentperformance('2018-02-28T15:50:00','2018-02-28T15:53:00')
# apiMethods.postContactsChatSessionTyping('1234')
# apiMethods.postContactsChatSessionTypingPreview('1234')
# apiMethods.getChatprofileByPOCId("2d102835-fa77-4c93-906e-cfd1889ed168")
# apiMethods.getThankYouForSkillId('12365')
# apiMethods.postContactChatSendEmail("maktum.pasha@hc8.com","rafiq.j@servion.com","test12222")
# apiMethods.getAddressBooks()
# apiMethods.createAddressBook()
# apiMethods.deleteAddressBook('1356')
# apiMethods.assignAddressBook('1356')
# apiMethods.getDynamicAddressBookEntries('1356')
# apiMethods.addDynamicAddressBookEntries('1356')
# apiMethods.deleteDynamicAddressBookEntry('1301','')
# apiMethods.getStandardAddressBookEntries('1356','2018-02-28T15:53:00','','','','','')
# apiMethods.createStandardAddressBookEntries('1356')
# apiMethods.updateStandardAddressBookEntries('1356')
# apiMethods.deleteAddressBookEntry('1356','')
# apiMethods.getAgentAddressBooks(agentId)
# apiMethods.getCampaignAddressBooks('1')
# apiMethods.getTeamAddressBooks(teamId)
# apiMethods.getAgents()
# apiMethods.changeAgentState(agentId)
# apiMethods.getAllAgentsSkills()
# apiMethods.deleteSkillsFromAgent(agentId)
# apiMethods.assignSkillsToAgent(agentId)
# apiMethods.modifySkillsForAgent(agentId)
# apiMethods.getAgentUnassignedSkills(agentId)
# apiMethods.getAgentsContactsBySkill()
# apiMethods.getAgentContactsBySkill(agentId)
# apiMethods.createCustomEvent(agentId)
# apiMethods.getQuickReplies()
# apiMethods.getAgentQuickReplies(agentId)
# apiMethods.getAgentMessages(agentId)
# apiMethods.getAgentIndicators(agentId)
# apiMethods.endAgentSession(agentId)
# apiMethods.getAgentsDialingPatterns()
# apiMethods.getAgentsStates()
# apiMethods.getTeams()
# apiMethods.getTeamById(teamId)
# apiMethods.deleteAgentsFromTeam(teamId)
# apiMethods.assignAgentsToTeam(teamId)
# apiMethods.deleteUnavailableCodesByTeam(teamId)
# apiMethods.getUnavailableCodesByTeam(teamId)
# apiMethods.assignUnavailableCodesToTeam(teamId)
# apiMethods.PutTeamidunavailablecodes(teamId)
# apiMethods.getAgentScheduledCallbacks(agentId)
# apiMethods.createScheduledCallback()
# apiMethods.deleteScheduledCallback(contactId)
# apiMethods.updateScheduledCallback(contactId)
# apiMethods.getSkillScheduledCallbacks(skillId)
# apiMethods.getBusinessUnit()
# apiMethods.getCountries()
# apiMethods.getStatesByCountryId('1')
# apiMethods.getDataDefinitionTypes()
# apiMethods.getFile()
# apiMethods.getFeedbackCategories()
# apiMethods.getHiringSources()
# apiMethods.createHiringSource()
# apiMethods.getHoursOfOperationProfiles()
# apiMethods.getHoursOfOperationProfileById('8')
# apiMethods.getLocations()
# apiMethods.getMediaTypes()
# apiMethods.getMediaTypesById('')
# apiMethods.getMessageTemplates()
# apiMethods.createMessageTemplate()
# apiMethods.getMessageTemplatesById('')
# apiMethods.updateMessageTemplate('')
# apiMethods.getPermissions()
# apiMethods.getPermissionsById(agentId)
# apiMethods.getPhoneCodes()
# apiMethods.getPointsOfContact()
# apiMethods.getPointsOfContactById('2d102835-fa77-4c93-906e-cfd1889ed168')
# apiMethods.getSecurityProfiles()
# apiMethods.getSecurityProfileById('8')
# apiMethods.getScripts()
# apiMethods.startScript('2')
# apiMethods.getServerTime()
# apiMethods.getTags()
# apiMethods.createTag()
# apiMethods.getTagById('8')
# apiMethods.updateTag('8')
# apiMethods.getTimeZones()
# apiMethods.getUnavailableCodes()
# apiMethods.getCampaigns()
# apiMethods.getCampaignById('1')
# apiMethods.getSkills()
# apiMethods.getSkillById(skillId)
# apiMethods.startPersonalConnectionSkill(skillId)
# apiMethods.stopPersonalConnectionSkill(skillId)
# apiMethods.getAgentsAssignedToSkills()
# apiMethods.deleteAgentsFromSkill(skillId)
# apiMethods.getAgentsAssignedToSkill(skillId)
# apiMethods.assignAgentsToSkill(skillId)
# apiMethods.modifyAgentsForSkill(skillId)
# apiMethods.getAgentsNotAssignedToSkill(skillId)
# apiMethods.getSkills()
# apiMethods.getCallDataBySkill(skillId)
# apiMethods.removeTagsFromSkill(skillId)
# apiMethods.getSkillTags(skillId)
# apiMethods.assignTagsToSkill(skillId)
# apiMethods.GetCPAManagement(skillId,'')
# apiMethods.PutCPAManagement(skillId)
# apiMethods.Getxssettings(skillId,'')
# apiMethods.Putxssettings(skillId)
# apiMethods.Getdeliverypreference(skillId,'')
# apiMethods.Putskilldeliverypreference(skillId)
# apiMethods.Getskillretrysetting(skillId,'')
# apiMethods.Putskillretrysetting(skillId)
# apiMethods.Getschedulesettings(skillId)
# apiMethods.Putschedulesettings(skillId)
# apiMethods.getChatTranscript(contactId)
# apiMethods.getEmailTranscript(contactId)
# apiMethods.endContact(contactId)
# apiMethods.monitorContact(contactId)
# apiMethods.recordContact(contactId)
# apiMethods.assignTagsToContact(contactId)
# apiMethods.getContactStateDescriptions()
# apiMethods.getContactStateDescriptionById('1')
# apiMethods.signalContact(contactId)
# apiMethods.getDncGroups()
# apiMethods.createDncGroup()
# apiMethods.getDncGroupById(groupId)
# apiMethods.updateDncGroup('292')
# apiMethods.getContributingSkillsForDncGroup(groupId)
# apiMethods.deleteContributingSkill(groupId,skillId)
# apiMethods.assignContributingSkill(groupId,skillId)
# apiMethods.deleteDncGroupRecords(groupId)
# apiMethods.getDncGroupRecords(groupId)
# apiMethods.postDncGroupRecords(groupId)
# apiMethods.getScrubbedSkillsForDncGroup(groupId)
# apiMethods.deleteScrubbedSkill(groupId,skillId)
# apiMethods.assignScrubbedSkill(groupId,skillId)
# apiMethods.postDncGroupsSearchPhoneNumber()
# apiMethods.getCallingLists()
# apiMethods.createCallingListMapping()
# apiMethods.deleteCallingList('1001')
# apiMethods.getCallingListById('1001')
# apiMethods.getCallingListAttempts('1001')
# apiMethods.resetAgentPassword(agentId)
# apiMethods.changeAgentPassword()
# apiMethods.queueCallback()
# apiMethods.createPromiseKeeper()
# apiMethods.createChatSession()
# apiMethods.endChatSession('65')
# apiMethods.getChatText('','')
# apiMethods.sendSingleChatMessage('')
# apiMethods.createWorkItem()
# apiMethods.getAgentsState()
# apiMethods.getAgentStateById(agentId)
# apiMethods.getContactsActive()
# apiMethods.getContactsParked()
# apiMethods.getContactsState()
# apiMethods.getSkillsActivity()
# apiMethods.getSkillActivityById(skillId)
# apiMethods.getAgentContactHistory(agentId)
# apiMethods.getRecentContactsInfo(agentId)
# apiMethods.getAgentLoginHistory(agentId)
# apiMethods.getAgentStateHistory(agentId)
# apiMethods.getAgentsPerformance()
# apiMethods.getAgentPerformanceById(agentId)
# apiMethods.getContactHistory(contactId)
# apiMethods.getCompletedContacts()
# apiMethods.callquality(contactId)
# apiMethods.getContactStateHistory(contactId)
# apiMethods.getContactCustomData(contactId)
# apiMethods.getSkillsSummary()
# apiMethods.getSkillSummaryById(skillId)
# apiMethods.getSkillsSlaSummary()
# apiMethods.getSkillSlaSummaryById(skillId)
# apiMethods.getReports()
# apiMethods.getReportJobs()
# apiMethods.startReportJob('53')
# apiMethods.postAgentPhoneDial(sessionID)
# apiMethods.agentEndCall(sessionID)
# apiMethods.muteAgentLeg(sessionID)
# apiMethods.unmuteAgentLeg(sessionID)
# apiMethods.agentPostCancelCallBack(sessionID,contactId,'')
# apiMethods.agentDialCallBack(sessionID,contactId)
# apiMethods.agentRescheduleCallBack(sessionID,contactId,'')
# apiMethods.agentAddChat(sessionID)
# apiMethods.agentAcceptContact(sessionID,contactId)
# apiMethods.agentActivateChat(sessionID,contactId)
# apiMethods.agentEndContact(sessionID,contactId)
# apiMethods.agentRejectContact(sessionID,contactId)
# apiMethods.agentSendChatText(sessionID,contactId,'')
# apiMethods.transferChatToAgent(sessionID,contactId,'')
# apiMethods.transferChatToSkill(sessionID,contactId,'')
# apiMethods.PostTyping(sessionID,contactId,'','')
# apiMethods.agentAddEmail(sessionID)
# apiMethods.agentEmailForward(sessionID,contactId,'','','','','','','','','','')
# apiMethods.agentEmailOutbound(sessionID,'','')
# apiMethods.agentEmailPark(sessionID,contactId,'','','','','','','','','','','','','','')
# apiMethods.agentEmailPreview(sessionID,contactId)
# apiMethods.agentEmailReply(sessionID,contactId,'','','','','','','','','','')
# apiMethods.agentEmailRestore(sessionID,contactId)
# apiMethods.agentEmailSend(sessionID,contactId,'','','','','','','','','')
# apiMethods.transferEmailToAgent(sessionID,contactId,'')
# apiMethods.transferEmailToSkill(sessionID,contactId,'')
# apiMethods.agentEmailUnPark(sessionID,contactId,'')
# apiMethods.agentDialerLogin(sessionID,'')
# apiMethods.agentDialerLogout(sessionID)
# apiMethods.agentSnooze(sessionID,contactId)
# apiMethods.agentIndependentDial(sessionID,contactId)
# apiMethods.agentDialOutcome(sessionID,contactId)
# apiMethods.phoneConsultAgent(sessionID,'','')
# apiMethods.phoneDialAgent(sessionID,'','')
# apiMethods.agentDialPhone(sessionID,'','','')
# apiMethods.phoneDialSkill(sessionID,'','')
# apiMethods.agentConferenceCall(sessionID)
# apiMethods.agentAcceptConsult(sessionID,contactId)
# apiMethods.agentAmdOveride(sessionID,contactId,'')
# apiMethods.agentSessionDisposition(sessionID,contactId,'','','','','','','')
# apiMethods.agentContactEnd(sessionID,contactId)
# apiMethods.agentContactHold(sessionID,contactId)
# apiMethods.agentSessionMask(sessionID,contactId)
# apiMethods.agentSessionRecord(sessionID,contactId)
# apiMethods.agentContactResume(sessionID,contactId)
# apiMethods.agentSessionUnmask(sessionID,contactId)
# apiMethods.transferCall(sessionID)
# apiMethods.phoneSendDtmf(sessionID,'','','')
# apiMethods.agentDeleteSession(sessionID)
# apiMethods.getNextEvent(sessionID)
# apiMethods.agentAddContact(sessionID,'','','')
# apiMethods.agentSession('4005150002','','','')
# apiMethods.agentSessionJoin('')
# apiMethods.agentContactActivate(sessionID,contactId)
# apiMethods.agentReSkill(sessionID,'')
# apiMethods.agentCustomData(sessionID,contactId,'','')
# apiMethods.agentFeedback(sessionID,'','','','')
# apiMethods.agentSessionState(sessionID,'')
# apiMethods.agentSessionBarge(sessionID)
# apiMethods.agentSessionCoach(sessionID)
# apiMethods.agentSessionMonitor(sessionID,'')
# apiMethods.agentSessionTakeOver(sessionID)
# apiMethods.agentEndVoiceMail(sessionID,contactId)
# apiMethods.agentPauseVoiceMail(sessionID,contactId)
# apiMethods.agentPlayVoiceMail(sessionID,contactId,'','')
# apiMethods.tranferVoicemailToAgent(sessionID,contactId,'')
# apiMethods.transferChatToSkill(sessionID,contactId,'')
# apiMethods.agentAcceptWorkitem(sessionID,contactId)
# apiMethods.agentEndWorkitem(sessionID,contactId)
# apiMethods.agentHoldWorkitem(sessionID,contactId)
# apiMethods.agentRejectWorkitem(sessionID,contactId)
# apiMethods.agentResumeWorkitem(sessionID,contactId)

#version 17
apiMethods.getBusinessunitTimezone()
apiMethods.getSuppresedContacts()
apiMethods.PostSuppresedContacts()
apiMethods.putbusinessunitTimezone()
apiMethods.PutSkillIDParameterTimezone('1234')
apiMethods.getTimeZoneBySkillId('1235')
#version 17
apiMethods.getBusinessunitTimezone()
apiMethods.getSuppresedContacts()
apiMethods.PostSuppresedContacts()
apiMethods.putbusinessunitTimezone()
apiMethods.PutSkillIDParameterTimezone('1234')
apiMethods.getTimeZoneBySkillId('1235')
apiMethods.deleteSkillBySkillIdAgentId('12365','12354')
#version 16
apiMethods.postjobSync()
apiMethods.GetmediaplaybackByID('21bf4a34-f768-45d4-aed6-6bd754dd49d2')
apiMethods.GetmediaplaybackBySegmentID('21bf4a34-f768-45d4-aed6-6bd754dd49d2','b171d215-a152-4572-bd45-56670cb7a859')
apiMethods.GetmediaplaybackContacts('master id 1')
apiMethods.getActiveFlag('1')
apiMethods.postWorkflowData()
apiMethods.getWorkflowDataById('56765')
apiMethods.putWorkflowDataById('56765')
apiMethods.putWorkflowDataByIdActivate('56765')
apiMethods.putWorkflowDataByIdDeactivate('56765')
apiMethods.getJobs()
apiMethods.postjobs()
apiMethods.getJobsByID('12345')
apiMethods.deleteSuppressedContactBySuppressedContactId('12345')
apiMethods.getSuppressedContactBySuppressedContactId('12345')
apiMethods.putSuppressedContactBySuppressedContactId('12345')
apiMethods.getContactsByIdHierachy('12345')

#version 18

apiMethods.getScripts18('','')
apiMethods.postScripts18('','')
apiMethods.putScripts18('','')
apiMethods.postScripts18Kick('')
apiMethods.getScripts18HistoryByName('')
apiMethods.PutSkillListManagement('')
apiMethods.getSkillParameters()
apiMethods.PutSkillCadenceSettings('')
apiMethods.getSkillSkillIdParameters('')
apiMethods.postSetDisposition('')
apiMethods.getBusinessunitOutboundRoutes()
#v19
apiMethods.getclientdata()
apiMethods.putclientdata()
apiMethods.postsmsoutbound('')
apiMethods.removeprospects('')
apiMethods.putpersistentcontacts('')
apiMethods.getagentsettings('')
apiMethods.getscriptsbyId('')
apiMethods.getscriptssearch()
apiMethods.deletescripts()
apiMethods.posttransformnumbers('')


#version 15
# apiMethods.getAccessKeys(agentId,'','','','')
# apiMethods.PostAccessKeys(agentId)
# apiMethods.getAccessKeysByID(accessKeyId)
# apiMethods.deleteAccessKeysByID(accessKeyId)
# apiMethods.patchAccessKeysByID(accessKeyId,'true')
# apiMethods.Postcampaigns()
# apiMethods.PutcampaignsByID('8913')
# apiMethods.PostcampaignsBySkill('8913')
# apiMethods.deletecampaignsBySkill('8913')
# apiMethods.getSmsHistoricalTranscripts(contactId,'1043')
# apiMethods.getSmsHistoricalContacts('4005150003','1043',skillId)
# apiMethods.PutUnavailableCodeByID('3588')
# apiMethods.PostHoursofOperation()
# apiMethods.PutHoursofOperationByID('12345')
# apiMethods.PostPointofContact()
# apiMethods.PutPointofContactByID('123335')
# apiMethods.PostUnavailableCodes()
# apiMethods.getPhonenumbers('','','')
# apiMethods.getDispositionSkills('','','','','','','')
# apiMethods.postEmailSaveDraft('WVVsLzlGTkc1T1hUTVpNVDlXR2Z2VzhVSzJrdTJ4djY5SDl2Q3lTQw==',contactId)
# apiMethods.postAddText('WVVsLzlGTkc1T1hUTVpNVDlXR2Z2VzhVSzJrdTJ4djY5SDl2Q3lTQw==')
# apiMethods.PutUnavailableCodeByIDTeams('12345')